apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
    - containerPort: 5432
