apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    name: votingapp-pod
    app: demo


