apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
  labels:
    app: votingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: votingapp-pod
      app: demo
  template:
    metadata:
      name: votingapp-pod
      labels:
              name: votingapp-pod
              app: demo
    spec:
      containers:
      - name: votingapp-oid
        image: dockersamples/examplevotingapp_vote
        ports:
                - containerPort: 80
