apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
